# Generated by Django 5.2.6 on 2025-10-03 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sales_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='price',
        ),
    ]
